# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheWear' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheWear
  pod 'Alamofire'
  pod 'YandexMobileAds', '7.18.1'
  pod 'YandexMobileAdsInstream', '0.63.0'
  pod 'AppMetricaAnalytics', '~> 5.14.0'
  
end
